apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: instaslice-operator-operand
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: instaslice-operator-operand
subjects:
- kind: ServiceAccount
  name: instaslice-operator-operand
  namespace: instaslice-system
