apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "inference.redhat.com/v1alpha1",
          "kind": "InstasliceOperator",
          "metadata": {
            "name": "cluster",
            "namespace": "instaslice-system"
          },
          "spec": {
            "emulatedMode": "false",
            "logLevel": "Normal",
            "managementState": "Managed",
            "operatorLogLevel": "Normal"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-29T19:27:55Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: instaslice-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: InstasliceOperator
      name: instasliceoperators.inference.redhat.com
      version: v1alpha1
    - kind: Instaslice
      name: instaslices.inference.redhat.com
      version: v1alpha1
  description: Instaslice Operator description. TODO.
  displayName: Instaslice Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - inference.redhat.com
          resources:
          - instaslices
          - instaslices/status
          - instaslices/finalizers
          - instasliceoperators
          - instasliceoperators/status
          - instasliceoperators/finalizers
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - events
          - namespaces
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          - issuers
          verbs:
          - create
          - get
          - list
          - patch
          - update
        serviceAccountName: instaslice-operator
      deployments:
      - name: instaslice-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: instaslice-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: instaslice-operator
            spec:
              affinity:
                podAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: instalice-operator
                      topologyKey: kubernetes.io/hostname
                    weight: 100
              containers:
              - args:
                - operator
                command:
                - /usr/bin/instaslice-operator
                env:
                - name: OPERATOR_NAME
                  value: instaslice-operator
                - name: RELATED_IMAGE_DAEMONSET_IMAGE
                  value: quay.io/ryan.phillips/instaslice-daemonset
                - name: RELATED_IMAGE_WEBHOOK_IMAGE
                  value: quay.io/ryan.phillips/instaslice-webhook
                image: quay.io/ryan.phillips/instaslice-operator
                imagePullPolicy: Always
                name: instaslice-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
                volumeMounts:
                - mountPath: /tmp
                  name: tmp
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: instaslice-operator
              volumes:
              - emptyDir: {}
                name: tmp
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - instaslice-operator
  links:
  - name: Instaslice Operator
    url: https://instaslice-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  relatedImages:
  - image: quay.io/ryan.phillips/instaslice-daemonset
    name: daemonset-image
  - image: quay.io/ryan.phillips/instaslice-webhook
    name: webhook-image
  version: 0.1.0
